services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: nest_app
    volumes:
      - /var/lib/docker/volumes/nest-app-volume/_data:/var/lib/mysql
    networks:
      - new
  nest:
    image: nest-app
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - new
networks:
  new:
